service: authorization-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  environment:
    AUTH_USER: ${env:AUTH_USER}
    AUTH_PASSWORD: ${env:AUTH_PASSWORD}

useDotenv: true

functions:
  basicAuthorizer:
    handler: dist/handler.basicAuthorizer